// Auth types
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GETPRODUCTANDCATEGORIES = 'GETPRODUCTANDCATEGORIES';
export const GETFAVORITES = 'GETFAVORITES';
export const GETCART = 'GETCART';
export const SETORDERCOUNT = 'SETORDERCOUNT';
export const RESETORDERCOUNT = 'RESETORDERCOUNT';
export const SETUSER = 'SETUSER';
export const PENDINGORDERS = 'PENDINGORDERS';
export const COMPLETEDORDERS = 'COMPLETEDORDERS';
export const LOADING = 'LOADING';